"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


DEBUG = env_bool('DJANGO_DEBUG', True)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-development-only')
if not DEBUG and SECRET_KEY == 'django-insecure-local-development-only':
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'DJANGO_ALLOWED_HOSTS',
        '127.0.0.1,localhost,testserver',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django_q',
    'core',
    'jobs',
    'cis_elements',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestIdMiddleware',
    'core.middleware.BackendTokenMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = []

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '0' if DEBUG else '60')),
        'CONN_HEALTH_CHECKS': not DEBUG,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

Q_CLUSTER = {
    'name': 'gene_family_backend',
    'workers': 2,
    'timeout': int(os.getenv('Q_CLUSTER_TIMEOUT', '300')),
    'retry': int(os.getenv('Q_CLUSTER_RETRY', '360')),
    'max_attempts': int(os.getenv('Q_CLUSTER_MAX_ATTEMPTS', '1')),
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
}

PLANTCARE_SUBMIT_URL = 'https://bioinformatics.psb.ugent.be/webtools/plantcare/cgi-bin/CallMat_onCluster.htpl'
PLANTCARE_EMAIL = os.getenv('PLANTCARE_EMAIL', os.getenv('MAIL_EMAIL', ''))
PLANTCARE_AUTH_CODE = os.getenv('PLANTCARE_AUTH_CODE', os.getenv('MAIL_PASSWORD', ''))
PLANTCARE_IMAP_HOST = os.getenv('PLANTCARE_IMAP_HOST', 'imap.qq.com')
PLANTCARE_IMAP_PORT = int(os.getenv('PLANTCARE_IMAP_PORT', '993'))
PLANTCARE_IMAP_FOLDER = os.getenv('PLANTCARE_IMAP_FOLDER', 'INBOX')
PLANTCARE_POLL_INTERVAL = int(os.getenv('PLANTCARE_POLL_INTERVAL', '10'))
PLANTCARE_MAX_POLLS = int(os.getenv('PLANTCARE_MAX_POLLS', '180'))
PLANTCARE_RESULT_TIMEOUT = int(
    os.getenv(
        'PLANTCARE_RESULT_TIMEOUT',
        str(PLANTCARE_POLL_INTERVAL * PLANTCARE_MAX_POLLS),
    )
)
PLANTCARE_POLL_BATCH_SIZE = int(os.getenv('PLANTCARE_POLL_BATCH_SIZE', '20'))
JOB_EXECUTION_LEASE_SECONDS = int(os.getenv('JOB_EXECUTION_LEASE_SECONDS', '330'))
JOB_POLL_LEASE_SECONDS = int(os.getenv('JOB_POLL_LEASE_SECONDS', '120'))
MAX_SEQUENCE_LENGTH = int(os.getenv('MAX_SEQUENCE_LENGTH', '1000000'))
MAX_ACTIVE_JOBS = int(os.getenv('MAX_ACTIVE_JOBS', '1000'))
PLANTCARE_ARCHIVE_MAX_MEMBERS = int(
    os.getenv('PLANTCARE_ARCHIVE_MAX_MEMBERS', '100')
)
PLANTCARE_ARCHIVE_MAX_FILE_SIZE = int(
    os.getenv('PLANTCARE_ARCHIVE_MAX_FILE_SIZE', str(20 * 1024 * 1024))
)
PLANTCARE_ARCHIVE_MAX_TOTAL_SIZE = int(
    os.getenv('PLANTCARE_ARCHIVE_MAX_TOTAL_SIZE', str(100 * 1024 * 1024))
)
ARTIFACT_ROOT = Path(os.getenv('ARTIFACT_ROOT', BASE_DIR / 'artifacts')).resolve()
BACKEND_API_TOKEN = os.getenv('BACKEND_API_TOKEN', '').strip()

SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if env_bool('DJANGO_TRUST_PROXY_SSL_HEADER', False)
    else None
)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {'()': 'core.logging.JsonFormatter'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}
